version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of your build.gradle or build.gradle.kts file
    schedule:
      interval: "weekly" # Options: "daily", "weekly", "monthly"
    open-pull-requests-limit: 5
