version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    # Look for `build.gradle` and `*.gradle.kts` files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automated"
    # Set review requirements
    reviewers:
      - "project-maintainers"
    # Allow up to 10 open pull requests at a time
    open-pull-requests-limit: 10
    # Define version update strategy
    versioning-strategy: auto

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"
      - "actions"
